# Generated by Django 3.0.8 on 2020-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quiztaker',
            options={'verbose_name_plural': 'Quiz Takers'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=120, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject Name'),
        ),
    ]
