# Generated by Django 3.0.8 on 2020-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200801_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(max_length=150, verbose_name='Option'),
        ),
    ]
